### ISSUE TITLE
Missing declaration files in TypeScript build

### ISSUE THREAD

**Issue by Hugoo** [lukso-network/tools-lsp-factory#26]
### I'm submitting a...

bug report

### Summary

Declaration files generated by TypeChain are not included by TS in the build folder.
This may lead to build error from user side.

### Other information (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

Flagged by Bon on Discord [link](https://discord.com/channels/359064931246538762/857568107820351508/908357948923850792) 

![image](https://user-images.githubusercontent.com/477945/141348869-f160dba3-393a-4444-b5cb-88f3f81f78f5.png)

### Resources 

- https://github.com/microsoft/TypeScript/issues/32624
- https://www.darraghoriordan.com/2021/01/03/copying-missing-files-typescript-build-deploy/

**Comment by rryter** [comment]
@Hugoo check this out too:
- https://github.com/dethcrypto/TypeChain/issues/430

It might be as simple as upgrading to TypeChain 6
