### ISSUE TITLE
nonce issues when using Ganache network

### ISSUE THREAD

**Issue by CallumGrindle** [lukso-network/tools-lsp-factory#47]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- Using lsp-factory with ganache test network causes nonce issues when deploying UniversalProfiles. Transaction nonces seem to be out by 2

- **Other information**

`the tx doesn't have the correct nonce. account has nonce of: 8 tx has nonce of: 10`

Similar problems occur when using a local hardhart network, though turning `automining` off fixes it. Possibly related. Problem persists when using ganache whether automining is on or off

**Comment by Hugoo** [comment]
I'll close as this is 2y and we changed a lot of things in between. If you still have the issue please reopen.
